### ISSUE TITLE
Touchscreen rotation not working

### ISSUE THREAD

**Issue by thatsitipl** [droidian-mt6765/adaptation-droidian-garden#4]
This is a new issue for the rotation issue on garden (only dandelion tested).

# The Problem
If you rotate the screen in phosh the image will rotate but the touchscreen won't.

# What i know
The input device for the touchscreen is (in my case) `/dev/input/event3`.
Phoc (compositor) is the programm for interacting with it.

If you now where the touchscreen input is taken (in the phoc source) please let me know.

**Comment by thatsitipl** [comment]
It has been a while but i finally found a solution.
The fix can be found here: https://github.com/thatsitipl/garden_rotation_helper.
Hope this helps anyone.

**Comment by FakeShell** [comment]
@thatsitipl Thank you for your efforts, i will review and let you know how we can add it to the package

**Comment by JeyKul** [comment]
@FakeShell barry, you 🔥

**Comment by FakeShell** [comment]
i have added it in the adaptation repo and linked your repo on the top of it. thanks for the contribution and good job

**Comment by thatsitipl** [comment]
I will test the changes as soon as the nightly images are fixed. Anyways thank you for creating this port and until i find other problems to fix.
